Book_project/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.urls import include

from user1 import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('user1/', include('user1.urls')),
    re_path(r'^', include(('user1.urls', 'user1'))),
    re_path(r'^$', views.LoginView.as_view()),
]

user1/urls.py
from django.urls import path, re_path
from user1 import views

urlpatterns = [
    # path('login/', views.login),   #FVB
    # path('register/', views.register, name='register'),
    path('login/', views.LoginView.as_view(), name='login'),   #CBV
    path('register/', views.RegisterView.as_view(), name='register'),
    path('exist_user/', views.exist_user),
    path('logout/', views.logout),

    path('book_list/', views.book_list, name='book_list'),
    # re_path(r'^book_list/(\d+)/(author)', views.book_list),
    re_path(r'^book_list/(?P<field_id>\d+)/(?P<field_type>publisher)', views.book_list),
    # 有名分组
    # re_path(r'^book_list/(\d+)/(author)', views.book_list),
    re_path(r'^book_list/(?P<field_id>\d+)/(?P<field_type>author)', views.book_list),
    # 有名分组
    path('del_book/', views.del_book, name='del_book'),
    re_path(r'^del_book(\d+)/(publisher)', views.del_book),
    re_path(r'^del_book(\d+)/(author)', views.del_book),

    path('add_book/', views.add_book, name='add_book'),
    re_path(r'^add_book(\d+)/(publisher)', views.add_book),
    re_path(r'^add_book(\d+)/(author)', views.add_book),

    re_path(r'^update_book/(?P<book_id>\d+)/(?P<field_id>\d+)/(?P<field_type>publisher)', views.update_book),
    re_path(r'^update_book/(?P<book_id>\d+)/(?P<field_id>\d+)/(?P<field_type>author)', views.update_book),
    # 这个必须放到下面，否则会截走上面两个，因为第一个也是正则
    re_path(r'^update_book/(?P<book_id>\d+)', views.update_book),

    path('publisher_list/', views.publisher_list, name='publisher_list'),
    path('del_publisher/', views.del_publisher, name='del_publisher'),
    path('add_publisher/', views.add_publisher, name='add_publisher'),
    re_path(r'^update_publisher/(\d+)', views.update_publisher),

    path('author_list/', views.author_list, name='author_list'),
    path('del_author/', views.del_author, name='del_author'),
    path('add_author/', views.add_author, name='add_author'),
    re_path(r'^update_author/(\d+)', views.update_author),


]

user1/models.py
from django.db import models

# Create your models here.
from django.utils import timezone

# 作者详情
class AuthorDetail(models.Model):
    age = models.IntegerField()
    addr = models.TextField()

# 出版社类
class Publisher(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=32)

    def __str__(self):
        return self.name

# 书类
class Book(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=32)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    publish_date = models.DateTimeField(default=timezone.now())

    # 书只能关联一个出版社，外键通常建在多的那一边
    publisher = models.ForeignKey(to='Publisher', on_delete=models.CASCADE)

    def __str__(self):
        return self.title

# 作者类
class Author(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=16)

    # 多对多
    books = models.ManyToManyField(to='Book', related_name='authors')

    detail = models.OneToOneField(to='AuthorDetail', null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.name



# 登录注册的用户信息
class UserInfo(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=16)
    pwd = models.CharField(max_length=32)

user1/views.py
from django.shortcuts import render,HttpResponse, redirect, reverse
from django.utils.decorators import method_decorator
from django.core import serializers
from django.views import View
import json
import datetime
import logging
from functools import wraps

# Create your views here.
from user1 import models
from user1 import myforms
from utils.mypage import MyPaginator
from utils.hash_pwd import salt_pwd

logger = logging.getLogger(__name__)
# 生成一个名为collect的实例
collect_logger = logging.getLogger('collect')

def check_login(func):
    # 判断用户有没有登录的装饰器
    @wraps(func)
    def inner(request, *args, **kwargs):
        # 拿到当前访问网址
        url = request.get_full_path()
        if request.session.get('user'):
            return func(request, *args, **kwargs)
        else:
            return redirect('/login/?next={}'.format(url))
    return inner

# def login(request):
#     login_form = myforms.LoginForm()
#     return render(request, 'user1/login.html', {'login_form': login_form})
#
# def register(request):
#     register_form = myforms.LoginForm()
#     return render(request, 'user1/register.html', {'register_form': register_form})

class LoginView(View):
    '''
        CBV 登录视图
        '''
    def get(self, request):
        login_form = myforms.LoginForm()
        return render(request, 'user1/login.html', {'login_form': login_form})

    def post(self, request):
        login_form = myforms.LoginForm(request.POST)
        if login_form.is_valid():
            username = login_form.cleaned_data.get('username')
            password = login_form.cleaned_data.get('password')
            password = salt_pwd(password, username)
            if models.UserInfo.objects.filter(name=username, pwd=password):
                # 设置session
                request.session['user'] = username
                # 设置session的失效时间
                # request.session.set_expiry(1800)

                # 登录成功，写log
                logger.info('用户: ' + username + '登录成功')

                next_url = request.GET.get('next')
                if next_url:
                    # 跳转到之前访问的页面
                    return redirect(next_url)
                else:
                    return redirect(reverse('user1:book_list'))
            else:
                # 登录失败，写log
                logger.error('用户： '+username+'登录时，用户名或者密码错误')

                return render(request, 'user1/login.html', {'login_form': login_form,
                                                            'error_msg': '用户名或密码错误'})
        else:
            return render(request, 'user1/login.html', {'login_form': login_form})

class RegisterView(View):
    '''
        CBV 注册视图
        '''
    # 逻辑上装饰器不该加在这里，但是可以验证装饰器加成功了
    # @method_decorator(check_login)
    def dispatch(self, request, *args, **kwargs):
        return super(RegisterView, self).dispatch(request, *args, **kwargs)

    def get(self, request):
        register_form = myforms.LoginForm()
        return render(request, 'user1/register.html', {'register_form': register_form})

    def post(self, request):
        register_form = myforms.LoginForm(request.POST)
        if register_form.is_valid():
            username = register_form.cleaned_data.get('username')
            password = register_form.cleaned_data.get('password')
            r_password = request.POST.get('r_password')
            if r_password == password:
                # 后台也需要判断用户名是否已经存在
                if not models.UserInfo.objects.filter(name=username).first():
                    password = salt_pwd(password, username)
                    models.UserInfo.objects.create(name=username, pwd=password)

                    # 注册成功之后，设置session登录状态
                    request.session['user'] = username

                    # 注册成功之后，写入log，并收集特定信息的日志
                    collect_logger.info('用户'+username+'注册')

                    return redirect(reverse('user1:book_list'))

            else:
                return render(request, 'user1/register.html', {'register_form': register_form,
                                                               'error_msg': '确认密码不符合'})
        return render(request, 'user1/register.html', {'register_form': register_form})

def exist_user(request):
    '''
        查看用户是否已经存在
        :param request:
        :return:
        '''
    if request.method == 'POST':
        username = request.POST.get('username')
        user_obj = models.UserInfo.objects.filter(name=username).first()

        reg = {'status': 1, 'msg': '用户已存在'} if user_obj else {
            'status': 0, 'msg': '用户不存在'
        }
        return HttpResponse(json.dumps(reg))

def logout(request):
    '''
        注销
        :param request:
        :return:
        '''
    request.session.delete()
    return redirect(reverse('user1:login'))

@check_login
def book_list(request, field_id=0, field_type='src'):
    '''
        书列表 三种情况 从book_list下来的书，从publisher_list下来的书  从author_list下来的书
        :param request:
        :param field_id:
        :param filed_type:
        :return:
        '''
    books = None

    filter_field = {
        'publisher': 'publisher_id',
        'author': 'author_id',
    }
    field_dict = {filter_field.get(field_type): field_id} if field_type in (
        'publisher', 'author') else {}
    books = models.Book.objects.filter(**field_dict).values(
        'id', 'title', 'price', 'publish_date', 'publisher__name').order_by('-id')

    ''' 注意上面得简化方法
        if field_type == 'publisher':
            books = models.Book.objects.filter(publisher_id=field_id).values(
            'id','title','price','publish_date','publisher__name').order_by('-id')
        elif field_type == 'author':
            books = models.Book.objects.filter(authors__id=field_id).values(
            'id','title','price','publish_date','publisher__name').order_by('-id')
        else:
             books = models.Book.objects.all().values('id', 'title', 'price', 
             'publish_date', 'publisher__name').order_by('-id')
    '''

    current_page_num = request.GET.get('page', 1)
    page_obj = MyPaginator(books, current_page_num)

    current_path = {'path': request.path}
    # 页码返回的是字典
    ret_dic = page_obj.show_page
    # 两个字典拼接
    ret_dic.update(current_path)

    # return render(request, 'user1/book_list.html', page_obj.show_page)
    return render(request, 'user1/book_list.html', ret_dic)

def del_book(request, field_id=0, field_type='src'):
    '''
        删除一本书，三种情况 从book_list下来的书，从publisher_list下俩的书  从author_list下来的书
        :param request:
        :param field_id:
        :param field_type:
        :return:
        '''
    delete_id = request.POST.get('delete_id')
    # 清除绑定关系
    if field_type == 'author':
        author_id = field_id
        author_obj = models.Author.objects.filter(id=author_id).first()
        try:
            author_obj.books.remove(delete_id)
            reg = {'status': 1, 'msg': '删除成功'}
        except Exception as e:
            reg = {'status': 0, 'msg': '删除失败'}
    # 其他情况都删除书   book_list  publisher_list 下来的书
    else:
        try:
            models.Book.objects.filter(id=delete_id).delete()
            reg = {'status': 1, 'msg': '删除成功'}
        except Exception as e:
            reg = {'status': 0, 'msg': '删除失败'}

    return HttpResponse(json.dumps(reg))

def add_book(request, field_id=0, field_type='src'):
    '''
        增加书
        :param request:
        :param field_id:
        :param field_type:
        :return:
        '''
    current_publisher_id = 0
    current_author_id = 0
    if field_type == 'publisher':
        current_author_id = int(field_id)
    elif field_type == 'author':
        current_author_id = int(field_id)

    book_form = myforms.BookForm()

    if request.method == 'POST':
        if current_publisher_id:
            # 前台设置select_disabled 不能传到后台了，因此需要这样做
            publisher_id = current_publisher_id
        else:
            publisher_id = int(request.POST.get('publisher'))

        if request.POST.get('publish_date') != '':
            publish_date = request.POST.get('publish_date')
        else:
            publish_date = datetime.datetime.now()

        book_form = myforms.BookForm(request.POST)

        if book_form.is_valid():
            book_obj = models.Book.objects.create(
                title=book_form.cleaned_data.get('title'),
                price=book_form.cleaned_data.get('price'),
                publish_date=publish_date,
                publisher_id=publisher_id,
            )
            if current_author_id:
                # 绑定多对多关系
                book_obj.authors.add(current_author_id)

            # return redirect(reverse('book:book_list'))
            # 因为有三种情况，分别跳到自己对应的页面下
            return redirect(request.path.replace('add_book', 'book_list'))

    publisher = models.Publisher.objects.all().values('id', 'name').order_by('-id')

    return render(request, 'user1/add_book.html', {'book_form': book_form,
                                             'publisher': publisher,
                                             "current_publisher_id": current_publisher_id})

def update_book(request, book_id, field_id=0, field_type='src'):
    # 修改书
    book = models.Book.objects.filter(id=book_id).first()
    book_form = myforms.BookForm()
    book_form.initial = {'title': book.title, 'price': book.price}

    if request.method == 'POST':
        if request.POST.get('publish_date') != '':
            publish_date = request.POST.get('publish_date')
        else:
            publish_date = datetime.datetime.now()

        book_form = myforms.BookForm(request.POST)

        if book_form.is_valid():
            models.Book.objects.filter(id=book_id).update(
                title=book_form.cleaned_data.get('title'),
                price=book_form.cleaned_data.get('price'),
                publish_date=publish_date,
                publisher_id=request.POST.get('publisher'),
            )
            # 有三种情况，分别跳到自己对应的页面下
            if field_type in ('publisher', 'author'):

templates/user1/add_author.html
{% extends 'base.html' %}

{% block title %}
    <title>add_author</title>
{% endblock title %}

{% block leftlist %}
{% endblock leftlist %}

{% block info %}
    <h3>add_author</h3>
{% endblock info %}

{% block con %}
    <form action="" method="post" novalidate autocomplete="off">
        {% csrf_token %}
        {% for field in author_form %}
            <p>
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                <span class="my-error-span">{{ field.errors.0 }}</span>
            </p>
        {% endfor %}

        <input class="pull-right btn btn-success" type="submit">
    </form>
{% endblock con %}

templates/user1/add_book.html
{% extends 'base.html' %}

{% block title %}
    <title>add_book</title>
{% endblock title %}

{% block leftlist %}

{% endblock leftlist %}

{% block info %}
    <h3>add_book</h3>
{% endblock info %}

{% block con %}
    <form action="" method="post" novalidate autocomplete="off">
        {% csrf_token %}
        {% for field in book_form %}
            <p>
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                <span class="my-error-span">{{ field.errors.0 }}</span>
            </p>
        {% endfor %}

        <p>
            {% load my_tag_filter %}
            <input type="hidden" id="hid_publisher_id" value="{{ current_publisher_id }}">
            <label for="id_publisher">出版社</label>
            <select name="publisher" id="id_publisher" class="form-control">
                {% for option in publisher %}
{#                    后来传过来的current_publisher_id|id_filter#}
                    {% if option.id == current_publisher_id|id_filter %}
                        <option selected value="{{ option.id }}">{{ option.name }}</option>
                    {% else %}
                        <option value="{{ option.id }}">{{ option.name }}</option>
                    {% endif %}
                {% endfor %}
            </select>
        </p>

        <p>
            <label for="publish_date">出版日期</label>
            <input class="form-control" type="date" name="publish_date" id="publish_date">
        </p>

        <input class="pull-right btn btn-success" type="submit">
    </form>
{% endblock con %}

{% block script %}
    {{ block.super }}
    <script type="text/javascript">
        $(function () {
            //默认显示当前时间
            var date = new Date();
            var dataString = date.getFullYear()+"-"+num(date.getMonth()+1)+"-"+num(date.getDate());
            $("$publish_date").val(dataString);

            // 有具体的某一个publisher时，下拉框不可选
            if(Number($('#hid_publisher_id').val()) >0){
                $("select[name=publisher]").attr('disabled', 'disabled');
            }
        });
        {#格式必须是 yyyy-MM-dd#}
        function num(obj) {
            if(obj < 10){
                return '0'+String(obj)
            }else{
                return obj
            }
        }
    </script>
{% endblock script %}

templates/user1/add_publisher.html
{% extends 'base.html' %}

{% block title %}
    <title>add_publisher</title>
{% endblock title %}

{% block leftlist %}

{% endblock leftlist %}

{% block info %}
    <h3>add_publisher</h3>
{% endblock info %}

{% block con %}
    <form action="" method="post" novalidate autocomplete="off">
        {% csrf_token %}
        {% for field in publisher_form %}
            <p>
                <label for="{{ field.id_for_label }}"{{ field.label }}></label>
                {{ field }}
                <span class="my-error-span">{{ field.errors.0 }}</span>
            </p>

            <input class="pull-right btn btn-success">
        {% endfor %}
    </form>
{% endblock con %}

templates/user1/author_list.html
{% extends 'base.html' %}

{% block title %}
    <title>author_list</title>
{% endblock title %}

{% block info %}
    <h3>authors</h3>
{% endblock info %}

{% block con %}
    <a href="{% url 'use1:add_author' %}" class="btn btn-info">创建</a>
    <table class="table table-bordered table-hover table-responsive table-striped">
        <thead>
            <tr>
                <th>序号</th>
                <th>ID</th>
                <th>姓名</th>
                <th>年龄</th>
                <th>地址</th>
                <th>修改操作</th>
                <th>删除操作</th>
            </tr>
        </thead>
        <tbody>
            {% for author in current_page_data %}
                <tr>
                    <td>{{ forloop.counter|add:seque }}</td>
                    <td>{{ author.detail_id }}</td>
                    <td><a href="/book_list/{{ author.id }}/author/">{{ author.name }}</a></td>
                    <td>{{ author.detail__age}}</td>
                    <td>{{ author.detail__addr }}</td>
                    <td><a href="/update_author/{{ author.id }}/" class="btn btn-success">修改</a> </td>
                    <td><button class="btn btn-dange my-delete">删除</button> </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock con %}

templates/user1/book_list.html
{% extends 'base.html' %}

{% block title %}
    <title>book_list</title>
{% endblock title %}

{% block info %}
    <h2>books</h2>
{% endblock info %}

{% block con %}
{#    这里使用了自定义的过滤器#}
    {% load my_tag_filter %}
    <a href="{{ path|path_filter }}" class="btn btn-info">创建</a>
    <table class="table table-bordered table-hover table-responsive table-striped">
        <thead>
            <tr>
                <th>序号</th>
                <th>ID</th>
                <th>名称</th>
                <th>价格</th>
                <th>出版社</th>
                <th>出版日期</th>
                <th>修改操作</th>
                <th>删除操作</th>
            </tr>
        </thead>
        <tbody>
            {% for book in current_page_data %}
                <tr>
                    <td>{{ forloop.counter|add:seque }}</td>
                    <td>{{ book.id }}</td>
                    <td>{{ book.title }}</td>
                    <td>{{ book.price }}</td>
                    <td>{{ book.publisher__name }}</td>
                    <td>{{ book.publish_date|date:'Y-m-d' }}</td>
{#                    <td><a href="/update_book/{{ book.id }}/" class="btn btn-success"></a> </td>#}
                    <td><a href="{{ path|update_path:book.id }}/" class="btn btn-success"></a> </td>
                    <td><button class="btn btn-danger my-delete">删除</button> </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock con %}

templates/user1/login.html
{% extends 'base.html' %}

{% block title %}
    <title>login</title>
{% endblock %}

{% block leftlist %}
    <div class="row">
        <ul class="nav nav-pills nav-stacked my-left-con">
            <li role="presentation" class="active"><a href="{% url 'user1:login' %}">登录</a> </li>
            <li role="presentation" ><a href="{% url 'user1:register' %}">注册</a> </li>
        </ul>
    </div>
{% endblock leftlist %}

{% block info %}
    <h3>欢迎来到</h3>
    <h3>图书管理系统</h3>
{% endblock %}

{% block cancel %}

{% endblock cancel %}

{% block con %}
    <form action="" method="post" autocomplete="off" novalidate>
        {% csrf_token %}
        {% for field in login_form %}
            <p>
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                <span class="my-error-span">{{ field.errors.0 }}</span>
            </p>
        {% endfor %}
        <span class="my-error-span">{{ error_msg }}</span>
        <input class="pull-right btn btn-success" type="submit">
    </form>
{% endblock con %}

{% block script %}
    <script type="text/javascript">
        $(function () {
            //页码不显示
            $('.my-page').css('display', 'none')
        })
    </script>
{% endblock %}

templates/user1/publisher_list.html
{% extends 'base.html' %}

{% block title %}
    <title>publisher_lisy</title>
{% endblock title %}

{% block info %}
    <h3>publisher</h3>
{% endblock info %}

{% block con %}
    <a href="{% url 'user1:add_publisher' %}" class="btn btn-info">创建</a>
    <table class="table table-bordered table-hover table-responsive table-striped">
        <thead>
            <tr>
                <th>序号</th>
                <th>ID</th>
                <th>名称</th>
                <th>修改操作</th>
                <th>删除操作</th>

            </tr>
        </thead>
        <tbody>
            {% for publisher in current_page_data %}
                <tr>
                    <td>{{ forloop.counter|add:seque }}</td>
                    <td>{{ publisher.id }}</td>
                    <td><a href="/book_list/{{ publisher.id }}/publisher/">{{ publisher.name}}</a></td>
                    <td><a href="/update_publisher/{{ publisher.id }}/" class="btn btn-success" >修改</a></td>
                    <td><button class="btn btn-danger my-delete">删除</button> </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock con %}

templates/user1/register.html
{% extends 'base.html' %}

{% block title %}
    <title>register</title>
{% endblock title %}

{% block leftlist %}
    <div class="row">
        <ul class="nav nav-pills nav-stacked my-left-con">
            <li role="presentation"><a href="{%  url 'user1:login' %}">登录</a> </li>
            <li role="presentation" class="active"><a href="{% url 'user1:register' %}">注册</a> </li>
        </ul>
    </div>
{% endblock leftlist %}

{% block info %}
    <h3>欢迎来到</h3>
    <h3>图书管理系统</h3>
{% endblock info %}

{% block cancel %}

{% endblock %}

{% block con %}
    <form action="" method="post" autocomplete="off" novalidate>
        {% csrf_token %}
        {% for field in register_form %}
            <p>
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                <span class="my-error-span">{{ field.errors.0 }}</span>
            </p>
        {% endfor %}

        <p id="r_pwd">
            <label for="r_password">确认密码</label>
            <input id="r_password" name="r_password" type="password" class="form-control">
            <span class="my-error-span">{{ error_msg }}</span>
        </p>

        <input class="pull-right btn btn-success" type="submit">
    </form>
{% endblock con %}

{% block script %}
    <script type="text/javascript">
        $(function () {
            // 页码不显示
            $('.my-page').css('display', 'none');
        });

        // 用户失去焦点之后，查看是否已经有该用户了
        $('#id_username').blur(function () {
            $.ajax({
                url:'/exist_user',
                type:'post',
                data:{'username':$('#id_username').val()},
                success:function (data) {
                    data = JSON.parse(data);
                    if(data.status ===1){
                        $('#id_username').siblings('span').text(data.msg)
                    }else {
                        $("#id_username").siblings('span').text('')
                    }
                }
            })
        })
    </script>
{% endblock script %}

templates/user1/update_author.html
{% extends 'base.html' %}

{% block title %}
    <title>update_author</title>
{% endblock title %}

{% block leftlist %}

{% endblock leftlist %}

{% block info %}
    <h3>update_author</h3>
{% endblock info %}

{% block con %}
    <form action="" method="post" novalidate autocomplete="off">
        {% csrf_token %}
        {% for field in author_form %}
            <p>
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                <span class="my-error-span">{{ field.errors.0 }}</span>
            </p>
        {% endfor %}

        <input class="pull-right btn btn-success" type="submit">
    </form>
{% endblock con %}

templates/user1/update_book.html
{% extends 'base.html' %}

{% block title %}
    <title>update_author</title>
{% endblock title %}

{% block leftlist %}

{% endblock leftlist %}

{% block info %}
    <h3>update_author</h3>
{% endblock info %}

{% block con %}
    <form action="" method="post" novalidate autocomplete="off">
        {% csrf_token %}
        {% for field in author_form %}
            <p>
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                <span class="my-error-span">{{ field.errors.0 }}</span>
            </p>
        {% endfor %}

        <input class="pull-right btn btn-success" type="submit">
    </form>
{% endblock con %}

templates/user1/update_publisher.html
{% extends 'base.html' %}

{% block title %}
    <title>update_publisher</title>
{% endblock title %}

{% block leftlist %}

{% endblock leftlist %}

{% block info %}
    <h3>update_publisher</h3>
{% endblock info %}

{% block con %}
    <form action="" method="post" novalidate autocomplete="off">
        {% csrf_token %}
        {% for field in publisher_form %}
            <p>
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                <span class="my-error-span">{{ field.errors.0 }}</span>
            </p>
            <input class="pull-right btn btn-success" type="submit">
        {% endfor %}
    </form>
{% endblock con %}